declare global {
	export namespace CSSStyleProperty {
		type Cursor =
			| 'alias'
			| 'all-scroll'
			| 'auto'
			| 'cell'
			| 'context-menu'
			| 'col-resize'
			| 'copy'
			| 'crosshair'
			| 'default'
			| 'e-resize'
			| 'ew-resize'
			| 'grabbing'
			| 'help'
			| 'move'
			| 'n-resize'
			| 'ne-resize'
			| 'nesw-resize'
			| 'ns-resize'
			| 'nw-resize'
			| 'nwse-resize'
			| 'no-drop'
			| 'none'
			| 'not-allowed'
			| 'pointer'
			| 'progress'
			| 'row-resize'
			| 's-resize'
			| 'se-resize'
			| 'sw-resize'
			| 'text'
			| 'URL'
			| 'vertical-text'
			| 'w-resize'
			| 'wait'
			| 'zoom-in'
			| 'zoom-out'
			| 'inital'
			| 'inherit';
	}
}

export {};
