name: Develop Groups 1 to Auto-Develop Branch

on:
  push:
    branches:
      - develop-G1

jobs:
  update:
    name: "Auto Merge Groups Develop 1 to auto-develop branch"
    runs-on: ubuntu-latest
    steps:
      - name: "🚚 - Checkout develop"
        uses: actions/checkout@v2

      - name: "🔀 - Merge develop-G1 to auto-develop"
        uses: mtanzi/action-automerge@v1
        id: mergeG1
        with:
          github_token: ${{ github.token }}
          source: 'develop-G1'
          target: 'auto-develop'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
